database.url=jdbc:postgresql://localhost:5432/simple_currency_exchange_service?currentSchema=simple_currency_exchange_service_heap
database.user=postgres
database.password=root

database.pool.size=10
database.pool.minIdle=2
database.connection.timeout=30000
database.idle.timeout=600000
database.max.lifetime=1800000
database.leak.detection.threshold=60000
database.validation.query=SELECT 1
database.prepStmt.cache.size=250
database.prepStmt.cache.sql.limit=2048
